export const RECEIVE_DECKS = 'RECEIVE_DECKS'
export const ADD_DECK = 'ADD_DECK'
export const REMOVE_DECK = 'REMOVE_DECK'
export const EDIT_DECK = 'EDIT_DECK'

export const ADD_QUESTION = 'ADD_QUESTION'
export const REMOVE_QUESTION = 'REMOVE_QUESTION'
export const EDIT_QUESTION = 'EDIT_QUESTION'

export const SUBMIT_SCORE = 'SUBMIT_SCORE'
export const START_QUIZ = 'START_QUIZ'
export const FINISH_QUIZ = 'FINISH_QUIZ'
export const SHOW_NEXT_CARD = 'SHOW_NEXT_CARD'
export const SHOW_PREVIOUS_CARD = 'SHOW_PREVIOUS_CARD'
